GameTrakR/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameTrakR.Code;

namespace GameTrakR.Controllers
{
    public class GamesController : Controller
    {
        public ActionResult Index()
        {
			GamesViewModel _viewModel = new GamesViewModel();
            return View(_viewModel);
        }

		public ActionResult Admin()
		{
			GamesViewModel _viewModel = new GamesViewModel();
			return View(_viewModel);
		}
		
		public ActionResult Groups()
		{
			GamesViewModel _viewModel = new GamesViewModel();
			return View(_viewModel);
		}		
    }
}

GameTrakR/Views/Games/Admin.cshtml
@{
	ViewBag.Title = "Game Administration - All Games";
}
@section scripts
{
	<script src="~/Scripts/GamesAdminHub.js" type="text/javascript"></script>
}
<button onclick="CreateNewGameDialog()" class="btn">
	New Game</button>
<ul id="gamesContainer">
	<li gameid="empty" style="display: none">
		<div class="container-fluid no-padding">
			<div class="row-fluid score">
				<div class="span6 centered">
					<div class="awayTeam">
					</div>
				</div>
				<div class="span6 centered">
					<div class="homeTeam">
					</div>
				</div>
			</div>
			<div class="row-fluid score scoreRow">
				<div class="span6 centered">
					<div class="awayScore">
					</div>
				</div>
				<div class="span6 centered">
					<div class="homeScore">
					</div>
				</div>
			</div>
			<div class="row-fluid inning">
				<div class="span12 centered">
					<div class="inningLabel">
					</div>
				</div>
			</div>
			<div class="row-fluid inningInfo">
				<div class="span6">
					<div class="outs pull-left">
					</div>
				</div>
				<div class="span6">
					<div class="countOnBatter pull-right">
					</div>
				</div>
			</div>
			<div class="row-fluid runnersOn">
				<div class="span12 centered">
					<div class="runnersOnBase">
					</div>
				</div>
			</div>
			<div class="row-fluid lastPlayInfo">
				<div class="span12 centered">
					<div class="lastPlay">
					</div>
				</div>
			</div>
			<button class="editGame btn">
				Edit Game Scenario</button>
		</div>
	</li>
	@foreach (GameTrakR.Code.Game game in Model.Games)
 {
		<li gameID="@game.GameID">
			<div class="container-fluid no-padding">
				<div class="row-fluid score">
					<div class="span6 centered">
						<div class="awayTeam">@game.AwayTeam</div>
					</div>
					<div class="span6 centered">
						<div class="homeTeam">@game.HomeTeam</div>
					</div>
				</div>
				<div class="row-fluid score scoreRow">
					<div class="span6 centered">
						<div class="awayScore">@game.CurrentGameScenario.AwayScore</div>
					</div>
					<div class="span6 centered">
						<div class="homeScore">@game.CurrentGameScenario.HomeScore</div>
					</div>
				</div>
				<div class="row-fluid inning">
					<div class="span12 centered">
						<div class="inningLabel">@game.CurrentGameScenario.InningLabel</div>
					</div>
				</div>
				<div class="row-fluid inningInfo">
					<div class="span6">
						<div class="outs pull-left">@game.CurrentGameScenario.OutsLabel</div>
					</div>
					<div class="span6">
						<div class="countOnBatter pull-right">@game.CurrentGameScenario.CountOnBatter</div>
					</div>
				</div>
				<div class="row-fluid runnersOn">
					<div class="span12 centered">
						<div class="runnersOnBase">@game.CurrentGameScenario.RunnersOnBase</div>
					</div>
				</div>
				<div class="row-fluid lastPlayInfo">
					<div class="span12 centered">
						<div class="lastPlay">@game.CurrentGameScenario.LastPlay</div>
					</div>
				</div>
				<button class="editGame" onclick="CreateScenarioDialog(@game.GameID)">
					Edit Game Scenario</button>
			</div>
		</li>
 }
</ul>
<button onclick="Reset()" class="btn">
	Reset Games List</button>

GameTrakR/Views/Games/Groups.cshtml
@{
    ViewBag.Title = "Game Groups Dashboard - Only Subscribed Games Update";
}
@section scripts
{
	<script src="~/Scripts/GamesGroupsHub.js" type="text/javascript"></script>
}

<ul id="gamesContainer">
	<li gameID="empty" style="display: none">
		<input class="manageSubscription" type="checkbox" /><div>Subscribed</div>
		<div class="container-fluid no-padding">
			<div class="row-fluid score">
				<div class="span6 centered">
					<div class="awayTeam"></div>
				</div>
				<div class="span6 centered">
					<div class="homeTeam"></div>
				</div>
			</div>
			<div class="row-fluid score scoreRow">
				<div class="span6 centered">
					<div class="awayScore"></div>
				</div>
				<div class="span6 centered">
					<div class="homeScore"></div>
				</div>
			</div>
			<div class="row-fluid inning">
				<div class="span12 centered">
					<div class="inningLabel"></div>
				</div>
			</div>
			<div class="row-fluid inningInfo">
				<div class="span6">
					<div class="outs pull-left"></div>
				</div>
				<div class="span6">
					<div class="countOnBatter pull-right"></div>
				</div>
			</div>
			<div class="row-fluid runnersOn">
				<div class="span12 centered">
					<div class="runnersOnBase"></div>
				</div>
			</div>
			<div class="row-fluid lastPlayInfo">
				<div class="span12 centered">
					<div class="lastPlay"></div>
				</div>
			</div>
		</div>
	</li>
@foreach (GameTrakR.Code.Game game in Model.Games)
{
	<li gameID="@game.GameID">
		<input class="manageSubscription" type="checkbox" onchange="ManageSubscription(@game.GameID)" /><div>Subscribed</div>
		<div class="container-fluid no-padding">
				<div class="row-fluid score">
					<div class="span6 centered">
						<div class="awayTeam">@game.AwayTeam</div>
					</div>
					<div class="span6 centered">
						<div class="homeTeam">@game.HomeTeam</div>
					</div>
				</div>
				<div class="row-fluid score scoreRow">
					<div class="span6 centered">
						<div class="awayScore">@game.CurrentGameScenario.AwayScore</div>
					</div>
					<div class="span6 centered">
						<div class="homeScore">@game.CurrentGameScenario.HomeScore</div>
					</div>
				</div>
				<div class="row-fluid inning">
					<div class="span12 centered">
						<div class="inningLabel">@game.CurrentGameScenario.InningLabel</div>
					</div>
				</div>
				<div class="row-fluid inningInfo">
					<div class="span6">
						<div class="outs pull-left">@game.CurrentGameScenario.OutsLabel</div>
					</div>
					<div class="span6">
						<div class="countOnBatter pull-right">@game.CurrentGameScenario.CountOnBatter</div>
					</div>
				</div>
				<div class="row-fluid runnersOn">
					<div class="span12 centered">
						<div class="runnersOnBase">@game.CurrentGameScenario.RunnersOnBase</div>
					</div>
				</div>
				<div class="row-fluid lastPlayInfo">
					<div class="span12 centered">
						<div class="lastPlay">@game.CurrentGameScenario.LastPlay</div>
					</div>
				</div>
			</div>
	</li>
}
</ul>

GameTrakR/Views/Games/Index.cshtml
@{
	ViewBag.Title = "Game Dashboard - All Games";
}
@section scripts
{
	<script src="~/Scripts/GamesIndexHub.js" type="text/javascript"></script>
}

<ul id="gamesContainer">
	<li gameID="empty" style="display: none">
		<div class="container-fluid no-padding">
			<div class="row-fluid score">
				<div class="span6 centered">
					<div class="awayTeam"></div>
				</div>
				<div class="span6 centered">
					<div class="homeTeam"></div>
				</div>
			</div>
			<div class="row-fluid score scoreRow">
				<div class="span6 centered">
					<div class="awayScore"></div>
				</div>
				<div class="span6 centered">
					<div class="homeScore"></div>
				</div>
			</div>
			<div class="row-fluid inning">
				<div class="span12 centered">
					<div class="inningLabel"></div>
				</div>
			</div>
			<div class="row-fluid inningInfo">
				<div class="span6">
					<div class="outs pull-left"></div>
				</div>
				<div class="span6">
					<div class="countOnBatter pull-right"></div>
				</div>
			</div>
			<div class="row-fluid runnersOn">
				<div class="span12 centered">
					<div class="runnersOnBase"></div>
				</div>
			</div>
			<div class="row-fluid lastPlayInfo">
				<div class="span12 centered">
					<div class="lastPlay"></div>
				</div>
			</div>
		</div>
	</li>
@foreach (GameTrakR.Code.Game game in Model.Games)
{
	<li gameID="@game.GameID">
		<div class="container-fluid no-padding">
				<div class="row-fluid score">
					<div class="span6 centered">
						<div class="awayTeam">@game.AwayTeam</div>
					</div>
					<div class="span6 centered">
						<div class="homeTeam">@game.HomeTeam</div>
					</div>
				</div>
				<div class="row-fluid score scoreRow">
					<div class="span6 centered">
						<div class="awayScore">@game.CurrentGameScenario.AwayScore</div>
					</div>
					<div class="span6 centered">
						<div class="homeScore">@game.CurrentGameScenario.HomeScore</div>
					</div>
				</div>
				<div class="row-fluid inning">
					<div class="span12 centered">
						<div class="inningLabel">@game.CurrentGameScenario.InningLabel</div>
					</div>
				</div>
				<div class="row-fluid inningInfo">
					<div class="span6">
						<div class="outs pull-left">@game.CurrentGameScenario.OutsLabel</div>
					</div>
					<div class="span6">
						<div class="countOnBatter pull-right">@game.CurrentGameScenario.CountOnBatter</div>
					</div>
				</div>
				<div class="row-fluid runnersOn">
					<div class="span12 centered">
						<div class="runnersOnBase">@game.CurrentGameScenario.RunnersOnBase</div>
					</div>
				</div>
				<div class="row-fluid lastPlayInfo">
					<div class="span12 centered">
						<div class="lastPlay">@game.CurrentGameScenario.LastPlay</div>
					</div>
				</div>
			</div>
	</li>
}
</ul>

GameTrakR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link href="../../Content/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
	<link href="../../Content/jquery.jgrowl.css" rel="stylesheet" type="text/css" />
	<link href="../../Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="../../Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
	@*<div>
		<ul id="ulMenu" style="width: 300px">
			<li>@Html.ActionLink("Games Dashboard", "Index", "Games")</li>
			<li>@Html.ActionLink("Games Admin", "Admin", "Games")</li>
			<li>@Html.ActionLink("Game Groups Dashboard", "Groups", "Games")</li>
		</ul>
	</div>*@
	<div class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container-fluid">
				@Html.ActionLink("GameTrakr", "Index", "Games", null, new { @class = "brand" })
				<ul class="nav">
					<li>@Html.ActionLink("Games Admin", "Admin", "Games")</li>
					<li>@Html.ActionLink("Game Groups Dashboard", "Groups", "Games")</li>
				</ul>
			</div>
		</div>
	</div>
	<h2>@ViewBag.Title</h2>
	<div>
		@RenderBody()
	</div>
	@*JQuery*@
	<script src="~/Scripts/jquery-1.9.1.js" type="text/javascript"></script>
	@*SignalR*@
	<script src="~/Scripts/jquery.signalR-1.0.1.js" type="text/javascript"></script>
	<script src="~/signalr/hubs"></script>
	@*JQuery UI*@
	<script src="~/Scripts/jquery-ui-1.10.1.js" type="text/javascript"></script>
	@*Bootstrap*@
	<script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>
	@*jGrowl*@
	<script src="~/Scripts/jquery.jgrowl.js" type="text/javascript"></script>
	@*Master JS Functions*@
	<script src="~/Scripts/master.js" type="text/javascript"></script>
	@RenderSection("scripts", required: false)
</body>
</html>